name: AuthPlus
version: '${project.version}'
main: com.authplus.AuthPlus
api-version: '1.19'
commands:
  login:
    description: Login command
  register:
    description: Register command
  premium:
    description: Premium command
